command: ['python', 'backend/src/app.py']

env:
  - name: "ENV"
    value: "PROD"
  - name: "STORAGE_MODE"
    value: "uc_native"
  - name: "APP_DEMO_MODE"
    value: "false"
  - name: "APP_AUDIT_VOLUME_ONLY"
    value: "true"
  - name: "APP_UC_MIRROR_ENABLED"
    value: "false"
  - name: "APP_UC_APP_SCHEMA"
    value: "ontos_test"

  - name: "PYTHONPATH"
    value: "./backend:${PYTHONPATH}"
  - name: "PYTHONUNBUFFERED"
    value: "1"
  - name: "FRONTEND_STATIC_DIR"
    value: "./static"

  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "DATABRICKS_VOLUME"
    valueFrom: "volume"

  - name: "APP_ADMIN_DEFAULT_GROUPS"
    value: '["admins", "users"]'
  - name: "APP_AUDIT_LOG_DIR"
    value: "/Volumes/${workspace.env.DATABRICKS_CATALOG}/${workspace.env.DATABRICKS_SCHEMA}/${workspace.env.DATABRICKS_VOLUME}/audit_logs"

  - name: "LLM_ENABLED"
    value: "False"
